[package]
name = "rustfuif"
version = "0.1.0"
authors = ["bart <bwillems@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0-alpha.2"
actix-cors = "0.3.0-alpha.1"
actix-files = { git = "https://github.com/actix/actix-web" }
actix-redis = { version = "0.9.0-alpha.1", features = ["web"] }
actix-rt = "1.0.0"
actix-service = "1.0.5"
actix-session = "0.4.0-alpha.1"
actix-threadpool = "0.3.1"
actix-web = "3.0.0-alpha.1"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99"
diesel = { version = "1.4", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4"
dotenv = "0.15.0"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
r2d2 = "0.8"
rand = "0.7"
redis = { version = "0.15", features = ["r2d2"] }
regex = "1.3"
rust-argon2 = "0.8"
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json = "1.0"
terminator = "0.1.0"
url = "2.1"

[patch.crates-io]
actix-redis = { git = 'https://github.com/BartWillems/actix-extras', features = ["web"]}

[profile.release]
lto = "thin"
