---
version: "3.4"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "rustfuif-dev"
      POSTGRES_USER: "rustfuif"
      POSTGRES_PASSWORD: "secret"
      TZ: "Europe/Brussels"
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - rustfuif_postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - "CMD"
        - "pg_isready"
        - "-d"
        - "rustfuif-dev"
        - "-U"
        - "rustfuif"
      timeout: 30s
      interval: 10s
      retries: 10

networks:
  backend:

volumes:
  rustfuif_postgres:
