---
version: "3.4"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "rustfuif-dev"
      POSTGRES_USER: "rustfuif"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - rustfuif_postgres:/var/lib/postgresql/data

networks:
  backend:

volumes:
  rustfuif_postgres: