---
version: "3.4"

services:
  rustfuif:
    image: rustfuif:latest
    environment:
      RUST_LOG: "debug"
      POSTGRES_USERNAME: "rustfuif"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DATABASE: "rustfuif"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "rustfuif"
      POSTGRES_USER: "rustfuif"
      POSTGRES_PASSWORD: "secret"
    networks:
      - backend

networks:
  backend:
