name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  publish:
    runs-on: ubuntu-18.04
    needs: ["test"]
    steps:
      - uses: actions/checkout@v2

      - name: Generate API Spec
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install -g redoc-cli
      - run: redoc-cli bundle api-spec/spec.yaml -o api-spec/index.html

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bartwillems/rustfuif
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          cache: "true"

      - name: Publish Docs
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: api-spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
