name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v2

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  DBSchema:
    name: Verify DB Schema
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://postgres:password@localhost/postgres"
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install SQLx CLI
        run: cargo install --version=0.5.2 sqlx-cli --no-default-features --features postgres --debug
      - name: Migrate database
        run: sqlx migrate run
      - name: Check sqlx metadata file
        run: cargo sqlx prepare --check

  publish:
    runs-on: ubuntu-20.04
    needs: ["test", "DBSchema"]
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bartwillems/rustfuif
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          cache: "true"
