name: Rust

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --document-private-items

      - name: generate-index-page
        run: |
          mv target/doc docs
          echo '<meta http-equiv="refresh" content="0; url=rustfuif/index.html">' > docs/index.html

  publish:
    runs-on: ubuntu-18.04
    needs: [build_docs]
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bartwillems/rustfuif/backend
          username: bartwillems
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          cache: "true"

      - name: Publish Docs
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
          keep_history: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
